### ISSUE TITLE
breaking changes when updating sbt-sassify to 1.4.12

### ISSUE THREAD

**Issue by nubz** [hmrc/play-frontend-govuk#86]
When attempting to update the version of `sbt-sassify` to `1.4.12`: 

`addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.4.12")`

with `play-frontend-govuk` version` 0.67.0-play-28`

`"uk.gov.hmrc"             %% "play-frontend-govuk"        % "0.67.0-play-28"`

we see a fail when running `sbt test` with the following error:

`...target/web/web-modules/main/webjars/lib/govuk-frontend/govuk/vendor/_sass-mq.scss:98:13: Error: 40.0625em isn't a valid CSS value.
[error]         on line 98 of target/web/web-modules/main/webjars/lib/govuk-frontend/govuk/vendor/_sass-mq.scss
[error] >>     @return ($px / $base-font-size) * 1em;
[error] 
[error]    ------------^
[error]     @return ($px / $base-font-size) * 1em;
[error]             ^
[error] one error found`

if we keep the `sbt-sassify` version as `1.4.11` there are no issues

**Comment by matthewmascord** [comment]
Hi @nubz , thanks for raising this issue. Looking at it, the problem seems to stem either from the Sass files in https://www.github.com/alphagov/govuk-frontend or https://www.github.com/irundaia/sbt-sassify. play-frontend-govuk is just including the govuk-frontend webjar assets transitively. I did notice this issue in the sbt-sassify backlog: https://github.com/irundaia/sbt-sassify/issues/37

Would it be worth trying v1.4.13 or later?

**Comment by nubz** [comment]
Hi @matthewmascord - yes! v1.4.13 works without issue, so it appears to be an issue with v1.4.12 only
